refactor compose
ObolNetwork/charon-distributed-validator-node pull request #130
Opened 2022-11-14 09:01 UTC by xenowits

Refactors `docker-compose.yml` to remove port mappings (except for grafana) and also removes jaeger and node-exporter. It moves the more "developer-focused" docker-compose file to a new `debug/` directory.

Also, updates the docker container versions.

ticket: https://github.com/ObolNetwork/charon-distributed-validator-node/issues/128

2022-11-14 09:46 UTC, corverroos requested changes

2022-11-14 09:46 UTC, corverroos commented on debug/.env.sample
> +#LIGHTHOUSE_VERSION=
lots of duplication here (with other .env file), not sure that is the best way to do it

2022-11-14 09:46 UTC, corverroos commented on debug/README.md
> +This folder contains a new `docker-compose.yml` file for developers to aid in debugging. This is meant to be configurable with sensible defaults that be overriden.
we should not duplicate the config, rather follow an additive approach where this folder adds to existing config.

2022-11-14 15:33 UTC, xenowits commented on compose-debug.yml
> +  node-exporter:
yeah, but we can have it at the least until we add container metrics

2022-11-14 15:37 UTC, xenowits commented
output of 
```sh
docker-compose -f docker-compose.yml -f compose-debug.yml up
```
<img width="1010" alt="Screenshot 2022-11-14 at 9 01 24 PM" src="https://user-images.githubusercontent.com/43061995/201700982-f97e0618-90a4-43b1-9f98-e52fbc775cd5.png">

2022-11-14 18:19 UTC, corverroos requested changes

2022-11-14 18:19 UTC, corverroos commented on README.md
> +      - `docker network create charon-distributed-validator-node_dvnode`
this is incorrect, the network prefix "charon-distributed-validator" comes from the folder name. Creating a network will not solve the issue. 

See above instructions:
```
      - Confirm the name of the exiting `charon-distributed-validator-node` docker network: `docker network ls`.
      - If it isn't `charon-distributed-validator-node-dvnode`, then update the `CHARON_DOCKER_NETWORK` env var in `.env` accordingly.
```

2022-11-14 18:19 UTC, corverroos commented on docker-compose.override.yml.sample
> +      # - ${GETH_PORT_P2P:-30303}:30303/tcp # P2P TCP
as I mentioned, no need to support overriding defaults in a file that is already an overide.

- Remove these overrides and provide hard coded values: `# - 30303:30303/tcp # P2P TCP`
- Remove the `GETH_PORT_*` override stubs in `.env.sample`

2022-11-14 18:19 UTC, corverroos commented on docker-compose.yml
> +      - CHARON_LOKI_ADDRESSES=${CHARON_LOKI_ADDRESSES:-}
enable this by default, same as jaeger previously

2022-11-14 18:19 UTC, corverroos commented on docker-compose.yml
> +      - CHARON_LOKI_ADDRESSES=${CHARON_LOKI_ADDRESSES:-}
`- CHARON_LOKI_ADDRESSES=${CHARON_LOKI_ADDRESSES-http://loki:3100/loki/api/v1/push} # Overriding to empty address allowed`

2022-11-14 18:19 UTC, corverroos commented on docker-compose.yml
> +      - CHARON_LOKI_ADDRESSES=${CHARON_LOKI_ADDRESSES:-}
note the missing `:` in the `{$FOO-bar}` vs `{$FOO:-bar}`

2022-11-14 18:19 UTC, corverroos commented on .env.sample
> +#CHARON_LOKI_ADDRESSES=
see comments below, but use the same comment as jaeger:
```
# Disable Loki log aggregation by setting an empty address.
#CHARON_LOKI_ADDRESSES=
```

2022-11-14 18:19 UTC, corverroos commented on compose-debug.yml
> +  jaeger:
enable jaeger in charon in this file:
```
services:
  charon:
    environment:
      - CHARON_JAEGER_ADDRESS=jaeger:6831
```

2022-11-14 18:19 UTC, corverroos commented on .env.sample
> +#CHARON_LOKI_ADDRESSES=
remove `CHARON_JAEGER_ADDRESS` above

2022-11-14 18:19 UTC, corverroos commented on docker-compose.yml
> +      --execution-endpoint=http://192.168.1.10:8551
hardcoded IP is not correct

2022-11-14 18:19 UTC, corverroos commented on docker-compose.yml
> -  loki:
do not remove loki, that was not part of the ticket

2022-11-15 04:33 UTC, xenowits commented on README.md
> +      - `docker network create charon-distributed-validator-node_dvnode`
yeah, should set the network in .env, new steps:
```
    - It occurs when docker can't find a network with the given name.
    - Verify if the docker network is present by running:
      - `docker network ls | grep charon-distributed-validator-node_dvnode`.
    - If there are no results, update the `CHARON_DOCKER_NETWORK` env var in `.env` accordingly:
      - `CHARON_DOCKER_NETWORK=charon-distributed-validator-node_dvnode`
```

2022-11-15 05:00 UTC, xenowits commented on docker-compose.yml
> +      - CHARON_LOKI_ADDRESSES=${CHARON_LOKI_ADDRESSES:-}
okay
```
${VARIABLE:-default} evaluates to default if VARIABLE is unset or empty in the environment.
${VARIABLE-default} evaluates to default only if VARIABLE is unset in the environment.
```

2022-11-15 05:32 UTC, xenowits commented on docker-compose.yml
> -  loki:
i was not sure as to include log aggregation as part of lean defaults. As discussed with the team, i'm adding back loki

2022-11-15 07:13 UTC, corverroos commented on README.md
> +docker-compose -f docker-compose.yml -f compose-debug.yml up
you need to include `docer-compose.overrides.yml` as well

2022-11-15 07:14 UTC, corverroos commented on README.md
>  5. How do I fix the `plugin "loki" not found` error?
can remove this right?

2022-11-15 07:17 UTC, corverroos commented on README.md
> +      - `CHARON_DOCKER_NETWORK=charon-distributed-validator-node_dvnode`
this is confusing, your example is setting the default value, which is the problem at this point. Suggest: `CHARON_DOCKER_NETWORK=<network obtained from 'docker network ls'>`

2022-11-15 07:19 UTC, corverroos commented on docker-compose.override.yml.sample
>    geth:
I get errors when using this:
 - ports cannot be empty
 - and subsequently the service-X cannot be empty 
 
 Suggest commenting out everything below `services`

2022-11-15 07:23 UTC, xenowits commented on README.md
>  5. How do I fix the `plugin "loki" not found` error?
yeah

2022-11-15 07:29 UTC, xenowits commented on docker-compose.override.yml.sample
>    geth:
yeah, the whole file needs to be commented out including `services:`

2022-11-15 07:36 UTC, xenowits commented on README.md
> +      - `CHARON_DOCKER_NETWORK=charon-distributed-validator-node_dvnode`
which network should be chosen if none exists? for ex: `docker network ls` gives:
```
NETWORK ID     NAME                            DRIVER    SCOPE
5cc259954324   493077459_compose               bridge    local
0291465e7045   1057849734_compose              bridge    local
7bbda699b8c3   2260650002_compose              bridge    local
00c47075ceb6   4023784422_compose              bridge    local
3e03359c3608   bridge                          bridge    local
0eb4ee0b17bd   charon-docker-compose_cluster   bridge    local
68154d9fc9c4   charon-release-06_compose       bridge    local
1f4205cc83c5   charon_validator                bridge    local
a9d469fcb9af   compose_compose                 bridge    local
61c81a1b6897   host                            host      local
a27a90dbb251   minikube                        bridge    local
5798ad791a45   none                            null      local
d0923f3970c5   soll_compose                    bridge    local
```

2022-11-15 08:35 UTC, corverroos commented on README.md
> +docker-compose -f docker-compose.yml -f compose-debug.yml -f docker-compose.override.yml up
swap override and debug

2022-11-15 08:36 UTC, corverroos commented on README.md
> +docker-compose -f docker-compose.yml -f compose-debug.yml -f docker-compose.override.yml up
and is this the only documentation you are adding for this compose-debug? It feels a bit light.

2022-11-15 08:36 UTC, xenowits commented on README.md
> +docker-compose -f docker-compose.yml -f compose-debug.yml -f docker-compose.override.yml up
gotcha, will add a new section for the "power users"

2022-11-15 08:37 UTC, corverroos commented on docker-compose.override.yml.sample
> +    env_file: [.env.charon.more]
why uncomment this? this will break since users do not have this file.

2022-11-15 08:37 UTC, xenowits commented on README.md
> +docker-compose -f docker-compose.yml -f compose-debug.yml -f docker-compose.override.yml up
would it be okay if I do it in a new PR?

2022-11-15 08:38 UTC, corverroos commented on README.md
> +docker-compose -f docker-compose.yml -f compose-debug.yml -f docker-compose.override.yml up
sure

2022-11-15 10:45 UTC, xenowits commented on README.md
> +docker-compose -f docker-compose.yml -f compose-debug.yml -f docker-compose.override.yml up
i'm gonna add the readme to this PR

2022-11-15 10:58 UTC, corverroos commented on README.md
> +docker-compose -f docker-compose.yml -f compose-debug.yml -f docker-compose.override.yml up
remove this (it belongs in the power user section)

2022-11-15 11:01 UTC, corverroos requested changes

2022-11-15 11:01 UTC, corverroos commented on compose-debug.yml
> +# Execute "docker-compose -f docker-compose.yml -f compose-debug.yml -f docker-compose.override.yml up".
order not correct

2022-11-15 11:01 UTC, corverroos commented on docker-compose.override.yml.sample
> +    env_file: [.env.charon.more]
we can't include it either since it will cause fresh checkouts to fail. Why did it work previously?

2022-11-15 11:11 UTC, xenowits commented on README.md
> +- We use the "Multiple Compose File" feature which provides a very powerful way to override any configuration in `docker-compose.yml` without needing to modify git-checked-in files since that results
okay, makes sense!

2022-11-15 11:14 UTC, xenowits commented on compose-debug.yml
> +# Execute "docker-compose -f docker-compose.yml -f compose-debug.yml -f docker-compose.override.yml up".
removed this comment from this file, as the readme explains everything

2022-11-15 11:25 UTC, xenowits commented on docker-compose.override.yml.sample
> +    env_file: [.env.charon.more]
i don't think it ever worked. i didn't use the override feature in this repo before so never encountered anything

2022-11-15 11:44 UTC, corverroos approved these changes

2022-11-15 11:45 UTC, merged