Update PR & Issue templates
ObolNetwork/charon-distributed-validator-node pull request #156
Opened 2023-02-03 14:14 UTC by thomasheremans

2023-02-07 12:29 UTC, dB2510 requested changes
In my mind cdvn and cdvc repos are very much user facing repositories. These are used as templates to run DVs, so I don't think it is justified to copy charon specific issue and PR templates to every repo. Can we keep it simple here?

2023-02-07 12:29 UTC, dB2510 commented on .github/pull_request_template.md
> +<!-- 🎉🚀 Thanks for submitting a PR!
Seems like this template is copied from charon, I think it won't applicable everywhere else. the reason being we don't push main features in this repo.

2023-02-07 12:29 UTC, dB2510 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +- [ ] Core team consensus on the proposed solution
Not needed in cdvn repo

2023-02-07 12:59 UTC, thomasheremans commented on .github/ISSUE_TEMPLATE/feature_request.md
> +- [ ] Core team consensus on the proposed solution
Thanks, removed from the other repos as well

2023-02-07 13:00 UTC, thomasheremans commented on .github/pull_request_template.md
> +<!-- 🎉🚀 Thanks for submitting a PR!
I think some structure to any PR is useful, I tried to remove any non-relevant item but let me know if there are any other that don't make sense

2023-02-07 13:00 UTC, thomasheremans commented on .github/pull_request_template.md
> +🧑‍🎓 Please review our contribution guide https://github.com/ObolNetwork/charon/blob/main/docs/contributing.md
Doesn't it make sense for this repo as well? Or maybe we should standardise the contribution guide?

2023-02-14 07:32 UTC, dB2510 commented on .github/pull_request_template.md
> +🧑‍🎓 Please review our contribution guide https://github.com/ObolNetwork/charon/blob/main/docs/contributing.md
> Doesn't it make sense for this repo as well?

yeah that contribution guide is written only charon in mind. 

> Or maybe we should standardise the contribution guide?

+1 for standard contribution guide. Also cdvn and cdvc repos are just for user deployments and not for feature development, so it doesn't make sense to have charon's contribution guide here.

2023-02-14 07:35 UTC, dB2510 approved these changes

2023-02-14 07:35 UTC, dB2510 commented
@thomasheremans I have removed pull request template for now. Will add if we need it. Merging this PR for now.

2023-02-14 07:36 UTC, merged