holesky ready cdvn
ObolNetwork/charon-distributed-validator-node pull request #254
Opened 2024-02-08 12:02 UTC by xenowits

* Adds `holesky` as the default network in CDVN
* Replaces `geth` with `nethermind` as the default EL client

2024-02-08 12:06 UTC, pinebit requested changes
Wrong port?

2024-02-08 12:06 UTC, pinebit commented on docker-compose.yml
> +      --Metrics.ExposePort=8008
6060 is specified in prometheus.yml.

2024-02-08 12:09 UTC, xenowits commented on docker-compose.yml
> +      --Metrics.ExposePort=8008
@pinebit thanks, fixed!

2024-02-08 12:10 UTC, pinebit approved these changes

2024-02-08 12:12 UTC, xenowits commented on docker-compose.yml
@pinebit do you think we should add `depends_on:` for `charon` depending on `lighthouse`? which ones specifically you mean?

2024-02-12 08:54 UTC, dB2510 approved these changes

2024-02-12 09:16 UTC, merged