*: multi cluster setup
ObolNetwork/charon-distributed-validator-node pull request #294
Opened 2024-11-23 19:38 UTC by KaloyanTanev

Multi cluster setup for CDVN.
Useful scripts that will help out users to use 1 EL + 1 CL with multiple Charons + VCs. Users will be able to spin up multiple clusters, without having to start separate EL and CL, saving up tremendous amount of resources.

2024-12-10 10:44 UTC, pinebit approved these changes

2024-12-10 10:44 UTC, pinebit commented on README.md
> +./multi_cluster/cluster.sh add {CLUSTER_NAME}
Would be great to have `Makefile` to run all these commands.

2024-12-10 15:42 UTC, aly-obol requested changes

2024-12-10 15:42 UTC, aly-obol commented on multi_cluster/setup.sh
> +  echo "./clsuters directory already exists. Cannot setup already set multi cluster CDVN."
typo

2024-12-10 15:42 UTC, aly-obol commented on multi_cluster/setup.sh
> +if test ./.env; then
test -f ./.env; then

2024-12-10 15:42 UTC, aly-obol commented on multi_cluster/setup.sh
> +trap 'cleanupClusterDir $?' EXIT
Deletion looks scary :) Can we backup or add some mitigation/protection?

2024-12-10 15:42 UTC, aly-obol commented on multi_cluster/cluster.sh
> +    echo "./clsuters directory does not exist. Run setup.sh first."
typo

2024-12-10 15:42 UTC, aly-obol commented on multi_cluster/cluster.sh
> +        if is_occupied=$(ss -taln | grep "$port"); then
grep -w to avoid false positives

2024-12-10 15:42 UTC, aly-obol commented on multi_cluster/cluster.sh
> +  if test ./.env; then
if test -f ./.env; then

2024-12-10 18:19 UTC, KaloyanTanev commented on README.md
> +./multi_cluster/cluster.sh add {CLUSTER_NAME}
I've added it! Not sure if it makes it easier, as we still require arguments and I personally am used to makefiles without arguments. But it does no harm regardless

2024-12-10 19:16 UTC, aly-obol approved these changes

2024-12-11 06:30 UTC, pinebit approved these changes

2024-12-12 10:54 UTC, gsora approved these changes

2026-01-30 18:28 UTC, OisinKyne commented
Closing as stale

2026-01-30 18:28 UTC, closed without merging